# Generated by Django 5.0.3 on 2024-11-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome de Usuário')),
                ('email', models.EmailField(max_length=40, verbose_name='Email do Usuário')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF do Usuário')),
                ('dateBirth', models.DateTimeField(verbose_name='Data de Nascimento do Usuário')),
                ('cellphone', models.CharField(max_length=14, verbose_name='Celular do Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('image', models.CharField(choices=[('I', 'Somente Imagem'), ('I+D', 'Imagem e Descrição'), ('I+D+C', 'Imagem, Descrição e Comentários')], default='I', max_length=5)),
            ],
        ),
    ]
