# Generated by Django 5.0.3 on 2024-11-26 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformav', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comentários'),
        ),
        migrations.AddField(
            model_name='post',
            name='postType',
            field=models.CharField(choices=[('I', 'Somente Imagem'), ('I+D', 'Imagem e Descrição'), ('I+D+C', 'Imagem, Descrição e Comentários')], default='I', max_length=5, verbose_name='Tipo de Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='plataformav.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post_images/', verbose_name='Imagem'),
        ),
    ]
