# Generated by Django 5.0.3 on 2024-11-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformav', '0004_post_comments_post_posttype_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.CharField(editable=False, max_length=12, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
