# Generated by Django 5.0.3 on 2024-11-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformav', '0005_alter_post_code_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=10, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.TextField(blank=True, editable=False, verbose_name='Comentários'),
        ),
    ]
