# Generated by Django 5.0.3 on 2024-11-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformav', '0011_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postType',
            field=models.CharField(choices=[('I', 'Somente Imagem'), ('I+C', 'Imageme Comentários'), ('I+D', 'Imagem e Descrição'), ('D+C', 'Descrição e Comentários'), ('I+D+C', 'Imagem, Descrição e Comentários')], default='I', max_length=5, verbose_name='Tipo de Post'),
        ),
    ]
