# Generated by Django 5.0.3 on 2024-11-26 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformav', '0012_alter_post_image_alter_post_posttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfeed',
            name='account',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='plataformav.account'),
        ),
        migrations.AlterField(
            model_name='postfeed',
            name='post',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='plataformav.post'),
        ),
    ]
