# Generated by Django 5.0.3 on 2024-11-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformav', '0013_alter_postfeed_account_alter_postfeed_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postType',
            field=models.CharField(choices=[('I', 'Somente Imagem'), ('I+C', 'Imagem e Comentários'), ('I+D', 'Imagem e Descrição'), ('D+C', 'Descrição e Comentários'), ('I+D+C', 'Imagem, Descrição e Comentários')], default='I', max_length=5, verbose_name='Tipo de Post'),
        ),
    ]
