# Generated by Django 5.0.3 on 2024-11-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformav', '0014_alter_post_posttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dateBirth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Nascimento do Usuário'),
        ),
    ]
