# Generated by Django 5.0.3 on 2024-11-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformav', '0016_alter_account_datebirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dateBirth',
            field=models.DateTimeField(verbose_name='Data de Nascimento do Usuário'),
        ),
    ]
